# Generated by Django 6.0.3 on 2026-04-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BallotPairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_seq", models.IntegerField()),
                ("pairing_seq", models.IntegerField()),
                ("passphrase", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
