# Generated by Django 6.0.3 on 2026-04-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("round", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotpairing",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
