# Generated by Django 6.0.4 on 2026-04-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("round", "0002_ballotpairing_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_draw", models.BooleanField(default=False)),
                ("display_team", models.BooleanField(default=False)),
                ("ballot_instructions", models.TextField(blank=True)),
                ("homepage_info", models.TextField(blank=True)),
                ("registration_open", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PendingSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("endpoint", models.CharField(max_length=1024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_log", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
